/**
 * Test bridge for verifying sprite-thumbnail rendering — no network, no auth, no external deps.
 *
 * Pages 1–20 come from a **uniform** sprite sheet (`/test-sprite.svg`): 20 equal cells, the simple
 * case. Pages 21–40 come from a **variable-size** sheet (`/test-sprite-var.svg`): a horizontal strip
 * of differently-proportioned tiles (mixed aspect ratios), which exercises the mixed-size galleries
 * that broke the naive "sheet height = tile height" assumption. If rendering is correct you should
 * see 40 distinct numbered tiles and the 21–40 cards should each take their own aspect ratio.
 *
 * The two sheets are generated by `@comical/host-server`'s router (`/test-sprite.svg`,
 * `/test-sprite-var.svg`) — the geometry constants below MUST stay in lockstep with them.
 */
import {
  BridgeBase,
  defineBridge,
  type BridgeInfo,
  type Page,
  type PageThumbnail,
  type PagedResults,
  type SeriesEntry,
  type SeriesInfo,
  type SeriesList,
} from "@comical/sdk";

// Uniform sheet — must match the /test-sprite.svg dimensions in host-server's router.ts.
const CELL_W = 200;
const CELL_H = 289;
const UNIFORM_COUNT = 20;

// Variable sheet — must match the /test-sprite-var.svg generation in host-server's router.ts.
// Tile i (0-based): width cycles 120/160/200/240/280, height cycles 300/250/200/150; top-aligned in
// a strip whose natural height is the tallest tile (300).
const VAR_COUNT = 20;
const VAR_SHEET_H = 300;
const varTileW = (i: number): number => 120 + (i % 5) * 40;
const varTileH = (i: number): number => VAR_SHEET_H - (i % 4) * 50;
const VAR_SHEET_W = Array.from({ length: VAR_COUNT }, (_, i) => varTileW(i)).reduce((a, b) => a + b, 0);

class TestSpritesBridge extends BridgeBase<Record<string, never>> {
  readonly info: BridgeInfo = {
    id: "test-sprites",
    name: "Test Sprite Thumbnails",
    version: "0.2.0",
    contractVersion: "1.0.0",
    languages: ["en"],
    nsfw: false,
    capabilities: ["direct", "lists"],
  };

  getSeriesDetails(_seriesId: string): Promise<SeriesInfo> {
    return Promise.resolve({
      id: "test-series",
      title: "Sprite Test Gallery",
      description:
        "40 pages. Pages 1–20 are equal cells from a uniform sprite sheet; pages 21–40 are " +
        "differently-proportioned tiles from a variable-size sheet (mixed aspect ratios). Correct " +
        "rendering: 40 distinct numbered tiles, with the 21–40 cards each taking their own shape.",
    });
  }

  getLists(): Promise<SeriesList[]> {
    return Promise.resolve([{ id: "all", name: "Test Gallery" }]);
  }

  getListItems(_listId: string, _page: number): Promise<PagedResults<SeriesEntry>> {
    return Promise.resolve({
      items: [{ id: "test-series", title: "Sprite Test Gallery" }],
      page: 1,
      hasNextPage: false,
    });
  }

  override getSeriesPages(_seriesId: string): Promise<Page[]> {
    const base = this.host.hostUrl ?? "http://localhost:3100";
    const pages: Page[] = [];

    for (let i = 0; i < UNIFORM_COUNT; i++) {
      const thumbnail: PageThumbnail = {
        kind: "sprite",
        sheetUrl: "/test-sprite.svg",
        x: i * CELL_W,
        y: 0,
        w: CELL_W,
        h: CELL_H,
        sheetWidth: CELL_W * UNIFORM_COUNT,
        sheetHeight: CELL_H,
      };
      pages.push({ index: i, imageUrl: `${base}/test-sprite.svg`, thumbnail });
    }

    let x = 0;
    for (let i = 0; i < VAR_COUNT; i++) {
      const w = varTileW(i);
      const h = varTileH(i);
      const thumbnail: PageThumbnail = {
        kind: "sprite",
        sheetUrl: "/test-sprite-var.svg",
        x,
        y: 0,
        w,
        h,
        sheetWidth: VAR_SHEET_W,
        sheetHeight: VAR_SHEET_H,
      };
      pages.push({ index: UNIFORM_COUNT + i, imageUrl: `${base}/test-sprite-var.svg`, thumbnail });
      x += w;
    }

    return Promise.resolve(pages);
  }
}

export default defineBridge((host) => new TestSpritesBridge(host));
